@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyDeliveryBook" as ReadOnlyDeliveryBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nReadOnlyUser" as ReadOnlyUser
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs
Class User
Class DeliveryBook

Class UniqueCompanyList
Class Company
Class Address
Class Email
Class Name
Class Phone
Class "Tag" as CompanyTag

Class UniqueDeliveryList
Class Delivery
Class Product
Class Deadline
Class "Tag" as DeliveryTag

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook
DeliveryBook .up.|> ReadOnlyDeliveryBook

ModelManager .up.|> Model
Model ..> ReadOnlyUserPrefs
Model ..> ReadOnlyUser
Model .down.> ReadOnlyAddressBook
Model .down.> ReadOnlyDeliveryBook
ModelManager -right-> "1" DeliveryBook
ModelManager -left-> "1" AddressBook
ModelManager -up-> "1" UserPrefs
ModelManager -up-> "1" User
UserPrefs .up.|> ReadOnlyUserPrefs
User .up.|> ReadOnlyUser

AddressBook *--> "1" UniqueCompanyList
UniqueCompanyList --> "*" Company
Company *--> Name
Company *--> Phone
Company *--> Email
Company *--> Address
Company *--> "*" CompanyTag

DeliveryBook *--> "1" UniqueDeliveryList
UniqueDeliveryList --> "*" Delivery
Delivery *--> Product
Delivery *-right-> "1" Company
Delivery *--> Deadline
Delivery *--> "*" DeliveryTag

Company -[hidden]--> I
UniqueCompanyList -[hidden]-> I

Delivery -[hidden]-> I
UniqueDeliveryList -[hidden]up-> I

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email
Email -[hidden]right-> Product
Product -[hidden]right-> Deadline
Deadline -[hidden]right-> Address

ModelManager --> "*" Company
ModelManager --> "*" Delivery
@enduml
